spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-config/test1
          search-paths: config
          username: hl010738@126.com
          password: she010738
#          basedir: /Users/zhanglong/Desktop/git-repo
  application:
    name: config-server

  rabbitmq:
    host: localhost
    port: 5672
    username: config-server
    password: config-server


#  security:
#    user:
#      name: hello
#      password: 123456

server:
  port: 7000


eureka:
  instance:
    instance-id: config-server
    appname: ${spring.application.name}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10097/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
